const express=require("express")
const router=express.Router()
const usuarioRuta=require('./UsuariosRuta')
const deportesRuta=require("./DeportesRuta")
const eventosRuta=require("./EventosRuta")
const gimansioRuta=require("./GimnasiosRuta")
const imagenesRuta=require("./ImagenesRuta")
const imagenEventoRuta=require("./ImagenesEventosRuta")
const licenciasRuta=require("./LicenciasRuta")
const usuarioRegistradoEvento=require("./usuario_registrado_evento")
const federados=require("./fedrados")
//rutas
router.use("/usuario",usuarioRuta)
router.use("/deportes",deportesRuta)
router.use("/eventos",eventosRuta)
router.use("/gimnasios",gimansioRuta)
router.use("/imagenes",imagenesRuta)
router.use("/imagenesevento",imagenEventoRuta)
router.use("/licencias",licenciasRuta)
router.use("/usuarioregistradoevento",usuarioRegistradoEvento)
router.use("/federados",federados)
module.exports=router